import type { DashboardData } from "@/types/dashboard";

export const dashboardData: DashboardData = {
  metrics: [
    {
      label: "الإنفاق خلال 30 يومًا",
      value: "$26,435.66",
      change: "ضمن السقف المعتمد",
      trend: "neutral",
      helper: "الحسابان المتصلان",
    },
    {
      label: "محادثات الرسائل",
      value: "15,299",
      change: "+8.4%",
      trend: "up",
      helper: "مقارنة بالفترة السابقة",
    },
    {
      label: "متوسط تكلفة المحادثة",
      value: "$1.73",
      change: "-11.2%",
      trend: "down",
      helper: "كلما انخفض كان أفضل",
    },
    {
      label: "إنفاق تحت المراقبة",
      value: "$4,899",
      change: "18.5%",
      trend: "neutral",
      helper: "ليس هدرًا مؤكدًا",
    },
  ],
  accounts: [
    {
      id: "account-1",
      name: "White Style — الحساب الأول",
      spend: 13862.86,
      conversations: 8478,
      cpr: 1.64,
      frequency: null,
      efficiency: 86,
      status: "healthy",
    },
    {
      id: "account-2",
      name: "White Style — الحساب الثاني",
      spend: 12572.8,
      conversations: 6821,
      cpr: 1.84,
      frequency: 5.75,
      efficiency: 68,
      status: "attention",
    },
    {
      id: "account-3",
      name: "White Style — الحساب الثالث",
      spend: 0,
      conversations: 0,
      cpr: 0,
      frequency: null,
      efficiency: 0,
      status: "critical",
    },
  ],
  actions: [
    {
      id: "action-1",
      title: "إيقاف إعلان شديد الهدر",
      detail: "تكلفة المحادثة وصلت إلى $67.48 مقابل معيار حساب $1.84.",
      account: "الحساب الثاني",
      amount: "$472.39",
      timestamp: "منذ 18 دقيقة",
      status: "executed",
      confidence: 99,
    },
    {
      id: "action-2",
      title: "خفض ميزانية مجموعة إعلانية 15%",
      detail: "التكلفة أعلى من المعيار منذ 3 أيام مع عينة كافية.",
      account: "الحساب الثاني",
      amount: "-$18 / يوم",
      timestamp: "منذ 43 دقيقة",
      status: "executed",
      confidence: 94,
    },
    {
      id: "action-3",
      title: "رفع ميزانية إعلان مستقر 12%",
      detail: "تكلفة أقل من المعيار بـ28% دون إشارة تشبع.",
      account: "الحساب الأول",
      amount: "+$14 / يوم",
      timestamp: "منذ ساعتين",
      status: "watching",
      confidence: 91,
    },
    {
      id: "action-4",
      title: "حماية حملة غير بيعية من الإيقاف",
      detail: "حملة ThruPlay مصنفة كوعي بالعلامة ولا تدخل في قواعد المحادثات.",
      account: "الحساب الأول",
      amount: "$258.54",
      timestamp: "اليوم، 09:20",
      status: "protected",
      confidence: 100,
    },
  ],
  spendSeries: [820, 905, 876, 960, 931, 1014, 942, 889, 918, 861, 846, 812],
  conversationSeries: [421, 465, 448, 492, 505, 532, 497, 510, 536, 548, 571, 596],
};
