"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Activity, BrainCircuit, LayoutDashboard, RefreshCw, Settings2, ShieldCheck, Target } from "lucide-react";
import { useState } from "react";
import type { ChartPoint } from "@/lib/dashboard-data";

const nav = [["/dashboard", "نظرة عامة", LayoutDashboard], ["/accounts", "الحسابات الإعلانية", Target], ["/agent-decisions", "قرارات Agent", BrainCircuit], ["/execution-log", "سجل التنفيذ", Activity], ["/safety-rules", "قواعد الحماية", ShieldCheck], ["/settings", "الإعدادات", Settings2]] as const;
export function Shell({ children }: { children: React.ReactNode }) { const path = usePathname(); return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">WS</div><div><strong>White Style</strong><span>Smart Agent</span></div></div><nav className="sidebar-nav">{nav.map(([href,label,Icon]) => <Link key={href} href={href} className={path === href ? "nav-item nav-item--active" : "nav-item"}><Icon size={19}/><span>{label}</span></Link>)}</nav><div className="sidebar-footer"><div className="profile-avatar">WS</div><div><strong>لوحة الإدارة</strong><span>Supabase connected</span></div></div></aside><main className="main-content">{children}</main></div>; }
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
export function PageHeader({ title }: { title: string }) { const router=useRouter(); return <header className="topbar"><div className="topbar-title"><div><p>بيانات مباشرة من Supabase</p><h1>{title}</h1></div></div><button className="sync-button" onClick={()=>router.refresh()}><RefreshCw size={16}/>تحديث البيانات</button></header>; }
function Chart({points}:{points:ChartPoint[]}) { if(!points.length) return <div className="empty-state">لا توجد بيانات أداء ضمن الفترة المحددة.</div>; const vals=points.map(x=>x.spend), max=Math.max(...vals,1); const pts=vals.map((v,i)=>`${i/(Math.max(vals.length-1,1))*100},${100-v/max*90}`).join(" "); return <div><svg className="simple-chart" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="2"/></svg><div className="chart-axis"><span>{points[0].date}</span><span>{points.at(-1)?.date}</span></div></div> }
export function DashboardClient({initial}:{initial:Awaited<ReturnType<typeof import("@/lib/dashboard-data").getDashboardData>>}) { const [days,setDays]=useState(30); const [data,setData]=useState(initial); const [loading,setLoading]=useState(false); async function change(value:number){setDays(value);setLoading(true);try { const r=await fetch(`/api/dashboard?days=${value}`,{cache:"no-store"}); if(!r.ok) throw new Error(); setData(await r.json()); } finally {setLoading(false)}} const s=data.stats; return <><PageHeader title="نظرة عامة"/><section className="metrics-grid">{[["الإنفاق خلال الفترة",money(s.spend)],["محادثات الرسائل",s.conversations.toLocaleString()],["متوسط تكلفة المحادثة",s.cost===null?"—":money(s.cost)],["الحسابات المتصلة",String(s.connected)]].map(([l,v])=><article className="metric-card" key={l}><div className="metric-label">{l}</div><strong className="metric-value">{v}</strong></article>)}</section><section className="content-grid"><article className="panel performance-panel"><div className="panel-heading"><div><span className="eyebrow">أداء يومي</span><h2>الإنفاق ومحادثات الرسائل</h2></div><div className="period-switch">{[7,14,30].map(v=><button disabled={loading} onClick={()=>change(v)} className={days===v?"active":""} key={v}>{v} يومًا</button>)}</div></div><div className="chart-summary"><div><span>إجمالي الإنفاق</span><strong>{money(s.spend)}</strong></div><div><span>المحادثات</span><strong>{s.conversations.toLocaleString()}</strong></div></div><Chart points={data.chart}/></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">حالة التشغيل</span><h2>المزامنة والـAgent</h2></div></div><div className="insight-list"><div>القرارات: {s.decisions}</div><div>التنبيهات غير المقروءة: {s.alerts}</div><div>آخر مزامنة: {s.lastSync?.finished_at ? new Date(s.lastSync.finished_at).toLocaleString("ar") : "لا توجد مزامنة"}</div><div>Autopilot: {s.config?.mode ?? "غير مُعد"} {s.config?.kill_switch ? "(Kill switch مفعّل)" : ""}</div></div></article></section><article className="panel accounts-panel"><div className="panel-heading"><h2>الحسابات الإعلانية</h2><Link className="text-button" href="/accounts">عرض التفاصيل</Link></div><Table accounts={data.accounts.slice(0,5)}/></article></> }
export function Table({accounts}:{accounts:import("@/lib/dashboard-data").AccountRow[]}){return <div className="account-table">{!accounts.length?<div className="empty-state">لا توجد حسابات إعلانية متاحة.</div>:<><div className="table-row table-head"><span>الحساب</span><span>الإنفاق</span><span>المحادثات</span><span>التكلفة</span></div>{accounts.map(a=><div className="table-row" key={a.id}><span>{a.name}<small>{a.connection_status}</small></span><strong>{money(a.spend)}</strong><strong>{a.conversations}</strong><strong>{a.conversations?money(a.spend/a.conversations):"—"}</strong></div>)}</>}</div>}
