"use client";
import { useMemo, useState } from "react";
import { PageHeader, Table } from "@/components/dashboard";
type RecordRow=Record<string, unknown>;
function value(value:unknown){return value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value)}
function name(row:RecordRow){const account=row.meta_ad_accounts as {name?:string}|null; return account?.name ?? "—"}
export function AccountsPage({accounts}:{accounts:Parameters<typeof Table>[0]["accounts"]}){const [q,setQ]=useState("");const [status,setStatus]=useState("all");const rows=useMemo(()=>accounts.filter(a=>(status==="all"||a.connection_status===status)&&`${a.name} ${a.meta_account_id}`.toLowerCase().includes(q.toLowerCase())),[accounts,q,status]);return <><PageHeader title="الحسابات الإعلانية"/><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو Meta ID"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">كل الحالات</option><option value="connected">connected</option><option value="pending">pending</option><option value="error">error</option></select></div><article className="panel"><Table accounts={rows}/></article></>}
export function DecisionsPage({rows,accounts}:{rows:RecordRow[];accounts:{id:string;name:string}[]}){const [q,setQ]=useState("");const [decision,setDecision]=useState("all");const shown=useMemo(()=>rows.filter(r=>(decision==="all"||r.decision===decision)&&`${r.reason} ${name(r)}`.toLowerCase().includes(q.toLowerCase())),[rows,q,decision]);return <><PageHeader title="قرارات Agent"/><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث في السبب أو الحساب"/><select value={decision} onChange={e=>setDecision(e.target.value)}><option value="all">كل القرارات</option>{[...new Set(rows.map(r=>String(r.decision)))].map(x=><option key={x}>{x}</option>)}</select></div><DataTable empty="لا توجد قرارات Agent حتى الآن." headers={["القرار","الحساب","السبب","الثقة","الحالة","وقت الإنشاء","وقت التنفيذ","النتيجة"]} rows={shown.map(r=>[r.decision,name(r),r.reason,`${r.confidence}%`,(r.agent_actions as RecordRow[]|undefined)?.[0]?.status,new Date(String(r.created_at)).toLocaleString("ar"),(r.agent_actions as RecordRow[]|undefined)?.[0]?.executed_at,(r.agent_actions as RecordRow[]|undefined)?.[0]?.error_message ?? (r.agent_actions as RecordRow[]|undefined)?.[0]?.verified_state])}/></>}
export function ExecutionPage({rows}:{rows:RecordRow[]}){return <><PageHeader title="سجل التنفيذ"/><DataTable empty="لا توجد عمليات مزامنة أو تنفيذ." headers={["المصدر","الحساب","الحالة","بدأ","انتهى","السجلات","الخطأ","cursor counts"]} rows={rows.map(r=>[r.source,name(r),r.status,r.started_at,r.finished_at,r.records_processed,r.error_summary,(r.cursor_state as RecordRow)?.counts])}/></>}
export function SafetyPage({rows}:{rows:RecordRow[]}){return <><PageHeader title="قواعد الحماية"/>{!rows.length?<article className="panel empty-state">لا توجد إعدادات حماية. أنشئ صفًا في agent_configs لإدارة Autopilot وحدوده.</article>:rows.map(r=><article className="panel settings-card" key={String(r.id)}><h2>{name(r) === "—" ? "إعدادات المنظمة الافتراضية" : name(r)}</h2><dl><dt>Autopilot</dt><dd>{value(r.mode)}</dd><dt>Kill switch</dt><dd>{r.kill_switch ? "مفعّل" : "غير مفعّل"}</dd><dt>أقصى زيادة للميزانية</dt><dd>{value(r.max_budget_change_percent)}%</dd><dt>الحد اليومي للزيادة</dt><dd>{value(r.daily_total_increase_percent)}%</dd><dt>الحد الأدنى لعمر الإعلان</dt><dd>لا يوجد عمود مخصص في schema</dd><dt>عتبة CPA الضعيف</dt><dd>{value(r.poor_cost_multiple)}× المعيار</dd><dt>عتبة إنفاق بلا نتائج</dt><dd>{value(r.no_result_pause_multiple)}× المعيار</dd></dl></article>)}</>}
export function SettingsPage({accounts,configs}:{accounts:RecordRow[];configs:RecordRow[]}){return <><PageHeader title="الإعدادات"/><article className="panel settings-card"><h2>الاتصال والحسابات</h2><p>تُقرأ بيانات الاتصال من Supabase. لا تُعرض مفاتيح API أو Meta tokens في الواجهة.</p><dl><dt>الحسابات</dt><dd>{accounts.length}</dd><dt>الحسابات المتصلة</dt><dd>{accounts.filter(x=>x.connection_status==="connected").length}</dd><dt>إعدادات Agent</dt><dd>{configs.length}</dd></dl></article></>}
function DataTable({headers,rows,empty}:{headers:string[];rows:unknown[][];empty:string}){return <article className="panel"><div className="data-table">{!rows.length?<div className="empty-state">{empty}</div>:<table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{value(c)}</td>)}</tr>)}</tbody></table>}</div></article>}
